### ISSUE TITLE
x32 and ARM builds?

### ISSUE THREAD

**Issue by denizsafak** [wojiushixiaobai/Python-Embed-Win64#1]
Hi. Is it possible to include x32 and ARM builds?

**Comment by wojiushixiaobai** [comment]
Arm64 seems to require additional steps.
- https://github.com/python/cpython/blob/3.11/Tools/msi/buildrelease.bat#L198

**Comment by denizsafak** [comment]
Thank you very much for adding x32 support. Do you think overriding that with something like that cause any problems? 
``` yml
- name: Reset Config
  if: env.build == '1'
  run: |
    sed -i 's@ --dirty@@g' PCbuild/pythoncore.vcxproj
    sed -i 's@--precompile@--precompile --include-pip --include-tcltk@g' Tools/msi/make_zip.proj
    sed -i 's@if "%BUILD_PLAT%" EQU "ARM64"@if "%BUILD_PLAT%" EQU "ARM64_OVERRIDE"@g' Tools/msi/buildrelease.bat
    cat Tools/msi/make_zip.proj | grep 'stable'
  shell: bash
  working-directory: cpython
```
Most versions have ARM embedded. I don't understand why they prevented this.
